apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
        - name: ping
          image: ping-image:1.0.1
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: app
spec:
  type: NodePort
  selector:
    app: ping
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
      nodePort: 30002