apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: pong-image:1.0.1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pong
  namespace: app
spec:
  type: NodePort
  selector:
    app: pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001